### ISSUE TITLE
Deprecation warning with Ruby 2.2

### ISSUE THREAD

**Issue by Ch4s3** [ulfurinn/wongi-engine#30]
.rvm/gems/ruby-2.2.0/bundler/gems/wongi-engine-ee696450d9af/lib/wongi-engine/wme.rb:129: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.

I'm not quite sure how to fix this. @ulfurinn any thoughts?

**Comment by Ch4s3** [comment]
Here's the ruby lang discussion of the issue https://bugs.ruby-lang.org/issues/7688

**Comment by ulfurinn** [comment]
Can you provide an example that triggers this? The unit tests don't.

**Comment by ulfurinn** [comment]
In particular, objects of which classes do you have in your templates or dataset? Looks like some of them may have an implementation of `<=>` that doesn't play well with others.

**Comment by Ch4s3** [comment]
Let me pull together an example that isn't straight out of my production app.
