### ISSUE TITLE
Enhancement requests: The balance of ruby collection iterators & forall runtime polymorphism

### ISSUE THREAD

**Issue by caldwecr** [ulfurinn/wongi-engine#31]
Pretty extensive users of wongi-engine. Glad to see that declarative collections are on the path to becoming first class with collectors.

Two items that would make our lives easier if they were available.

1 #map and #inject for tokens matching a rule

Consider this circumstance

````
facts_matching_my_rule = rules[:my_rule].tokens
facts_matching_my_rule.each do |token|
    # yada yada
end
````

Many times I find myself wishing that #map and #inject also worked in these circumstances. I imagine that #map! isn't feasible although it does sound appealing.

2 forall_eval (or if this already exists, then documentation and examples)

The wongi-engine rules can be frustratingly incompatible with a notion of rule inheritance - and while you can combine queries and rules to, in some cases, achieve single inheritance it would really be more idiomatic if we had access to the equivalent of instance_eval for a particular rule - it seems that the notion of a rule's singleton is roughly parallel to a class's singleton. Even if the notion of runtime polymorphism of rules (specifically the forall sections) is infeasible then the addition of an explicit rule inheritance operator would be splendid.

**Comment by ulfurinn** [comment]
1. This already works. BetaNode#tokens returns an Enumerator. I added a spec in bb79980 as an example.
2. I don't understand what you mean. Rules are in no way classes, and applying OOP concepts does not naturally work, in my mind. If you mean extending the same base rule with different additional matchers, then, yes, that is feasible, although you already can achieve this with surrogate facts. Can you give me an example of how you intend to use this, to make sure we're talking about the same thing?

**Comment by caldwecr** [comment]
Thank you for your response. I am planning to reply soon with some details regarding the second topic.
