### ISSUE TITLE
Trouble using gen

### ISSUE THREAD

**Issue by Ch4s3** [ulfurinn/wongi-engine#32]
I have a rule like: 
```` ruby
    eligible_person = rule "Eligible person" do
      forall {
        has :Person, "sex", "Male"
        has :_, "age", :age
        greater :age, 50
      }
      make {
        gen :Person, "eligible_person", true
      }
    end
````

and another rule like:
```` ruby
    identify_thing = rule "Identify thing" do
      forall {
        has :User, "role", "special_role_for_this_thing"
        maybe :Person, "eligible_person", :EligiblePerson
        maybe :Person, "special_marker", :SpecialMarker
        maybe :Person, "other_thing", :OtherThing

        assert do |token|
          (token[:EligiblePerson] == true && token[:SpecialMarker] != nil) || (token[:OtherThing] != nil && token[:OtherThing] > 25)
        end
      }
    end
````

I load the engine with facts iteratively, but the effect is basically as follows:

```` ruby
engine = Wongi::Engine.create
engine << ["Joe", "sex", "Male"]
engine << ["Joe", "age", 61]
engine << ["user", "role", "special_role_for_this_thing"]
````
Then I add the rules roughly like the following:

````ruby
rules.each do |rule|
  engine << rule
end
```

They run, but when I pry into the `assert` in `"Identify thing"` I see that `token[:EligiblePerson]  = nil`. I'm looking for `engine.productions["Identify thing"].size > 0` and can't seem to make the rules work together. However, when I step through Wongi with the [debugger in pry](https://github.com/deivid-rodriguez/pry-byebug), I can see the template for `gen` making EligiblePerson, and apparently adding it to the engine. But, I can't access that fact for some reason. When I call: 
````ruby
engine.facts.map{|fact| p fact}
````

I see all of the facts I entered with `<<`, but not the one made by `gen`.

Any thoughts on what I'm doing wrong?

*Edit for catching nil on token[:OtherThing]
I was able to paste this all into the console to reproduce the behavior I'm seeing in my actual application.*

**Comment by ulfurinn** [comment]
Your eligible rule will never fire.

`:_` is a catch-all placeholder, you probably wanted to put `:Person` there.

Variables are symbols starting with a capital letter, so `:age` will only match the actual symbol `:age`.

**Comment by Ch4s3** [comment]
Thanks, @ulfurinn that got me most of the way there.

I updated the first rule to:
```` ruby
eligible_person = rule "Eligible person" do
  forall {
    has :Person, "sex", "Male"
    has :Person, "age", :Age
    greater :Age, 50
  }
  make {
    gen :Person, "eligible_person", true
  }
end
````

And I added a print statement into the second for debugging:

````ruby
assert do |token|
  p "Here is the token #{token[:EligiblePerson]}"
  (token[:EligiblePerson] == true && token[:SpecialMarker] != nil) || (token[:OtherThing] != nil && token[:OtherThing] > 25)
end
````

I'm loading these rules in from the database by calling a class method that returns a `Wongi::Engine::ProductionRule`, basically like:
````ruby
rules_to_run = where(name: selected_rules)
rules_to_run.find_each do |rule|
  engine << rule.instantiate_rule #instantiate_rule returns a ProductionRule
end
```
It prints the following:
````
"Here is the token "
"Here is the token "
````
And it adds the fact `[:Person, "eligible_person", true]` twice.

And ````ruby engine.productions["Identify thing"].size > 0 ```` evaluates to `false`.

Any clues?

**Comment by ulfurinn** [comment]
> And engine.productions["Identify thing"].size > 0 evaluates to false.

If those three facts are all you have in the dataset, then, yes, it would. There is nothing to match against that would bind to SpecialMarker or OtherThing, so the `assert` will always fail.

**Comment by ulfurinn** [comment]
> And it adds the fact [:Person, "eligible_person", true] twice.

Where are you reading that from?

And, in any case, if it did, it would be inconsequential. The dataset is, well, a set.

**Comment by ulfurinn** [comment]
Duplicate tokens occur though. I'll look into this.

**Comment by Ch4s3** [comment]
Sorry, that was a bad example of the assert I'm using in production. It's more like:

````ruby
engine << ["Joe", "sex", "Male"]
engine << ["Joe", "age", 61]
engine << ["user", "role", "special_role_for_this_thing"]
engine << ["Joe", "job", "developer"]
````

````ruby
assert do |token|
  p "Here is the token #{token[:EligiblePerson]}"
  (token[:OtherThing] != nil ) || (token[:EligiblePerson] == true && token[:Job] != nil)
end
````

In production I have 9 or 10 variables arranged like A OR B OR C OR (D AND E). In this particular rule no single fact is required, and several combinations of 2 or 3 should make the whole thing valid.

Thanks, for taking a look!

**Comment by ulfurinn** [comment]
Here's a full example that works for me: https://gist.github.com/ulfurinn/84b4bb26a47ba49f0e55

The duplicate token issue is tricky. I suggest you switch to v0.1.0.alpha1, there has been a fairly big internal overhaul that fixed a number of potential issues and would be rather pointless to try to backport.

**Comment by ulfurinn** [comment]
Also, as a suggestion, consider swapping `maybe`/`assert` for `any`/`option`. Something like this:

```ruby
    any {
      option {
        has :Person, "eligible_person", true
        has :Person, "job", :Job
      }
      option {
        has :Person, "other_thing", :OtherThing
        greater :OtherThing, 20
      }
    }
```

It will generate separate tokens for each pathway, this is something you may need to consider.

My basic guidelines are:
* only drop to ruby blocks if no existing matcher satisfies the need
* prefer small rules that activate each other with helper facts to mammoth rules that build up large tokens

**Comment by Ch4s3** [comment]
Thanks! That looks like it will do what I need, and I'll take a look at v0.1.0.alpha1. Do you need any help with docs on this stuff?
