### ISSUE TITLE
Help writing rules

### ISSUE THREAD

**Issue by steverob** [ulfurinn/wongi-engine#33]
I have the following situation in a Rails app.

I have `Companies` that perform many services (`has_and_belongs_to_many :services`).
I have `Incidents` that need certain services (again `has_and_belongs_to_many :services`).

Now I need to find all Companies that offer the services needed by a certain Incident. Im not able to wrap my head around the DSL and come up with rules. Would love some help with this :+1:

**Comment by steverob** [comment]
This could be the facts - 

```
engine << [ "CompanyA", "offers", "serviceA" ]
engine << [ "CompanyB", "offers", "serviceB" ]
engine << [ "CompanyA", "offers", "serviceB" ]
engine << [ "CompanyB", "offers", "serviceC" ]
engine << [ "IncidentA", "requires", "serviceC" ]
engine << [ "IncidentA", "requires", "serviceA" ]

```

**Comment by ulfurinn** [comment]
One way of doing it:

```ruby
q = engine.query( "demo" ) {
  search_on :Incident
  forall {
    has :Incident, "requires", :Service
    has :Company, "offers", :Service
  }
}

engine.execute "demo", Incident: "IncidentA"
q.tokens.each do |token|
  puts token[:Company]
end
```

**Comment by ulfurinn** [comment]
Or do you mean that a single company should satisfy all requirements?

**Comment by steverob** [comment]
Thanks @ulfurinn. yes that's exactly it. It should satisfy all requirements i.e we need companies that offer all the services required by the Incident. Would love a pointer as to how I can do that :)

**Comment by ulfurinn** [comment]
In that case:

```ruby
engine.query( "demo" ) {
  search_on :Incident
  forall {
    has :Incident, "requires", :Service
    has :Company, "offers", :Service
    none {
      has :Incident, "requires", :OtherService
      neg :Company, "offers", :OtherService
    }
  }
}
```

Translated back into English, "if a company offers one of the services, there do not exist any other services that are required but not offered by the same company".

**Comment by steverob** [comment]
Wow. That's awesome man. Thanks for this :+1:

**Comment by steverob** [comment]
@ulfurinn I understand now how to write these rules. But I still cant understand how I can use Rails models in place of these strings (services, incidents & companies). Do I just use a string representation of the model - like `service_#{service.id}`?

Are there any best practices to load the facts into the engine? Initializing the engine in the app, etc.

**Comment by ulfurinn** [comment]
Any Ruby value with a sane implementation of operator `==` can be used inside fact triples, expect symbols with special meanings.
