### ISSUE TITLE
Implementation of wongi

### ISSUE THREAD

**Issue by blanchma** [ulfurinn/wongi-engine#34]
This is my use case:

I have many events in the system like:

user1, create, meeting1
meeting1, has, tag1
meeting1, has, tag2
meeting1, has, tag3
user1, create, meeting2
user2, create, meeting3

The rules are dynamic because is based in the interest of each user. Example:

user3 wants to know of create meetings but with tag 1 or 2.

Now, my questions and search for suggestions. I guess there's a way to write rules like the example case for user3. So not a problem. But:

1. Any time I create a new event I should add this event as triple in the engine and the engine should have the rules already loaded, no?
2. Given the rule set can be large, did anyone implement an architecture where the engine rules is keep alive in memory and react to new facts

**Comment by blanchma** [comment]
I was thinking I don't need a dynamic rule. But the "dynamic" is actually data, not logic. So I could add

engine << [user1, like, tag1]

And the rule could be like
for_all {
  fact :userX, meeting_created, :meetingY
  fact :meetingY, has, :tag1
  fact :userY, like, :tag1
  assert do |token|
      token[:userX] != token[:userY]
    end
}


I don't want to load in memory the meetings and users (at least I don't like it now because a possible performance issue in a high load context) so I guess I can replace them for something like
{id: 1, class: :user}
{id: 2, class: :meeting}

**Comment by blanchma** [comment]
But I still have the question of how to handle this in a way I have the engine loaded with data waiting for more data and watching the rules doesn't have new results.

**Comment by steverob** [comment]
+1. Would love to know how this is done. :+1:

**Comment by ulfurinn** [comment]
Well, you could have the engine running in a separate process and communicate with messages, for example. Lots of different approaches here. I don't really understand how I can answer this.
