### ISSUE TITLE
Dynamically add Conditions to a Rule

### ISSUE THREAD

**Issue by mjalvarez** [ulfurinn/wongi-engine#35]
Hi,

Is it possible to create a rule with dynamic conditions? Something like the following...

```ruby
engine = Wongi::Engine.create

engine << ["Joe", "gender", "Male"]
engine << ["Joe", "age", 61]

# Records of conditions with predicates and constraints, as defined by the user.
conditions = Condition.all 

el = engine.rule( "Eligible person" ) do
  forall {
    has :Person, "age", :Age
    conditions.each do |condition|
      #add condition here, e.g. `has :_, condition.predicate, condition.match_value`
    end
  }
end
```

Thanks!

**Comment by ulfurinn** [comment]
You can do it, but it will only be evaluated once. If your intent is that the set of conditions may change in runtime and the rule should reflect that, the only way to make it work is to create a new rule each time.

**Comment by mjalvarez** [comment]
Thanks @ulfurinn , I did try it initially, and it does seem to not work as I hoped. I settled to create a rule for each condition instead:

```ruby
engine = Wongi::Engine.create

engine << ["Joe", "gender", "Male"]
engine << ["Joe", "age", 61]

# Records of conditions with predicates and constraints, as defined by the user.
conditions = Condition.all 
conditions.each do |condition|
  engine.rule( "Eligible person" ) do
    forall {
      has :Subject, :Predicate, :Object
      assert do |token|
        condition.met?(token)
      end
  }
  end
end
```

Not sure if this is the right thing to do this. `condition.met?` has to check each fact, and I have to add conditionals to verify if the condition is appropriate for a given fact. It becomes more and more expensive as the number of facts grow.

Would you have any suggestions how to make this a lot better? I believe I'm doing it wrong :)

Thanks!

**Comment by ulfurinn** [comment]
Yes, this is abuse. I don't see why your original proposal wouldn't work, unless I'm missing something crucial from the larger context of what you're trying to build.

**Comment by ulfurinn** [comment]
Ah, I misread the snippet. I don't quite see how such one-condition rules could achieve anything interesting at all. Please explain more.

**Comment by mjalvarez** [comment]
Sorry, just got back in the grid. 

I agree, the second snippet does not utilize the engine as it should, and all facts go through all generated rules even if they are not applicable.

Here's what I am trying to do:

I have records of conditions that look like...
```ruby
<Condtion id: 1, attribute: 'first_name', operator: 'equal', match_value: 'Joe'>
<Condtion id: 2, attribute: 'points', operator: 'greater_than', match_value: '1000'>
<Condtion id: 3, attribute: 'last_name', operator: 'starts_with', match_value: 'di'>
```

I also need a flag that dictates whether All Conditions must match or Any Conditions match, so I put it in another model `Rule`

```ruby
<Rule condition_rule: 'has'>
```
*Rule* `has_many :conditions`.
Initially I had `'and'` and `'or'` as possible values of `condition_rule`, but if I were to use the rule engine, I think it would be better to make it more direct as `'has'` and `'maybe'`.

Given those and the snippet below...
```ruby
el = engine.rule( "Eligible person" ) do
  forall {
    conditions.each do |condition|
      #add condition here, e.g. `has :_, condition.operator, condition.match_value`
    end
  }
end
```

In my mind, the conditions and the rule I generated should be like:
```ruby
el = engine.rule( "Eligible person" ) do
  forall {
    conditions.each do |condition|
       has 'first_name', 'equal', 'Joe'
       has 'points', 'greater_than', 1000
       has 'last_name', 'starts_with', 'di'
    end
  }
end
```
I tried the snippet above, ignoring the `condition_rule` at first by explicitly using `'has'`, but all the facts  I generated (true and false) just seem to slide through the rule. 


Ideally I would like to be able to generate a rule with conditions based on the records in the DB, governed by the `'condition_rule'`

If `'condition_rule'` is `'has``, then
```ruby
forall {
  has 'first_name', 'equal', 'Joe'
  has 'points', 'greater_than', 1000
  has 'last_name', 'starts_with', 'di'
}
```

If `'condition_rule'` is `'maybe``, then
```ruby
forall {
  maybe 'first_name', 'equal', 'Joe'
  maybe 'points', 'greater_than', 1000
  maybe 'last_name', 'starts_with', 'di'
}
```

But I don't know how to do it yet :) Perhaps this?
```ruby
forall{
  send(rule.condition_rule, [attribute, condition.operator, condition.match_value] )
}
```

Are these doable? Or I just don't have an idea what I could do with the engine?

Thanks for your time @ulfurinn! I am really looking forward to using this engine in production! :)

**Comment by ulfurinn** [comment]
These are very strange rules. In particular because they're not a single variable binding in sight, which I suppose could still work but makes for a very peculiar workflow. Could you show an example of facts you were testing them with?

**Comment by ulfurinn** [comment]
Also, predicates do not result in method calls against subjects, because it looks like what you're trying to do.
