### ISSUE TITLE
wongi:engine development status

### ISSUE THREAD

**Issue by andycu2015** [ulfurinn/wongi-engine#36]
how active is wongi:engine development? I came from the Drools background and its development is very active.  

we're in the process of moving to Ruby on Rails and wongi:engine is a possible replacement for Drools. I'm wondering how active is it in term of development and maintenance since we plan to use it in production.

Thanks

**Comment by ulfurinn** [comment]
I respond to bug reports in a timely manner, and occasionally to feature requests if I find them reasonable, but it's a one-man hobby project with a tiny userbase, and I've got other things in my life to take care of. My priorities shift between projects depending on user interest. Adjust your expectations accordingly. If you need something the engine doesn't do, let me know and we'll work something out.
