### ISSUE TITLE
Question: how to avoid duplicate action

### ISSUE THREAD

**Issue by lauraeci** [ulfurinn/wongi-engine#38]
The wongi-engine is really awesome.  Its working great except in this case I get the same action called repeatedly and I'm not sure how to avoid that.  Any suggestions would be very appreciated.  
I have a relationship, where an Event can have an Actor and a Manager.   The action should fire for a fact where the Event is in the same location as the manager and the actor.  When there is only one location it seems to work but when there are multiple locations then its called duplicate times.  Not sure if this is what I should be doing.  I changed the scenario a bit because I don't want to publish production code.  I have a database of rules and I'm trying to check each event against the matching rules and execute code for matching events.

Thanks!
-Laura
self.engine.rule do
    forall {
      has :Event, 'actor_distance', :Actor_distance
      has :Event, 'manager_distance', :Manager_distance
      has :Event, 'manager', :Manager
      has :Event, 'actor', :Actor
      has :Event, 'location', :Location
      has :Manager, 'location', :Location
      has :Manager, 'bill_by_event', 1
      has :Manager, 'manager_limit', :Manager_limit
      has :Manager, 'manager_lt', :Manager_lt
      has :Manager, 'manager_gte', :Manager_gte
    }
    make {
      action { |token|
        Rails.logger.info("Rules met #{token[:Event]} for manager bill_by_event.")
      }
    }
  end
end

18EEN9E1 status is scheduled
18EEN9E1 actor_distance is 0.1683
18EEN9E1 location is Downtown Chicago
18EEN9E1 actor is actor-49
18EEN9E1 venue is 267
18EEN9E1 manager manager-37
actor-49 bill_by_event is 1
actor-49 location is Downtown Chicago
actor-49 location is San Francisco
manager-37 location is San Fransisco

**Comment by ulfurinn** [comment]
This is the intended behaviour. Every possible combination of matched facts will generate a new result set.

**Comment by ulfurinn** [comment]
What you can do is something like this:

```ruby
...
make {
  gen :Event, 'picked_manager', :Manager
}
```

and then act on the picked_manager statements. Those will only be generated one per event-manager pair.

**Comment by lauraeci** [comment]
Thanks!  That is very helpful. :100:
