### ISSUE TITLE
Generating a fact's object value based on a previous fact

### ISSUE THREAD

**Issue by tonywok** [ulfurinn/wongi-engine#39]
Hey there, I'm new to rule engines and the Rete algorithm. Learning about it and reading your code has been really fun. Anyway, now that I'm playing  around with some rules I was wondering if it were possible to programmatically create new facts based on variables. In other words, is something similar to this supported?

*Note*: using `gen` to illustrate what I'm doing, but aware it won't work since it supports static or variable object values.

```ruby
engine.rule "example" do
    forall {
        has :A, "some_value", :B
    }
    make {
        gen :A, "some_other_value", :B + 1
    }
end

engine << ["test", "some_value", 10]
# resulting in creation of ["test", "some_other_value", 11]
```

Perhaps this should be done with `make` and `action`? Although then it seems like you'd lose easy access to your template variables.

I suppose you could do `token.wme.(subject|predicate|object)`:

```ruby
engine.rule "example" do
    forall {
        has :A, "some_value", :B
    }
    make {
        action { |token| engine << [token.wme.subject, "some_other_value", token.wme.object + 1] }
    }
end
```
Is there a better or more appropriate way? It's also possible that my question is misinformed. Either way, thanks for your time and again, appreciate the work you've done :) Let me know if the example is too contrived and I'd be glad to conjure up a more realistic one.

**Comment by tonywok** [comment]
ah, I hadn't considered using `assign` for this:

```ruby
engine.rule "example" do
  forall {
    has :A, "some_value", :B
    assign :C do |token|
      token[:B] + 1
    end
  }
end
```
Having tried a few things, I think what I'm doing is computing "dynamic" facts from initially static facts. Is this an abuse of the library? Semantically, I don't think `assign` achieves this since it's not resuling in `engine << [:A, "some_other_value", (:B + 1)]`

*Note*: I'm aware ruby can't execute `:B + 1` - it's only there to illustrate my intent.

**Comment by ulfurinn** [comment]
A combination of `assign` and `gen` is fine.

An assert inside `action` is not recommended since it's harder to maintain data integrity that way.

**Comment by tonywok** [comment]
@ulfurinn Ha, I was almost there. Now that you mention it I think `assign` + `gen` is exactly what I wanted. Thanks.
