### ISSUE TITLE
String matches should be exact, not fuzzy

### ISSUE THREAD

**Issue by lukegalea** [ulfurinn/wongi-engine#40]
We have a rule:

```has :Event, 'program_name', "Level 1 Coaching Certification v2"```

It's matching facts like:

```[:Event, 'program_name', "Level 1 Coaching Certification"]```

(note missing v2)

**Comment by ulfurinn** [comment]
Please provide a full example.

**Comment by abargnesi** [comment]
@lukegalea You may be perceiving that fact because it's asserted separately from productions of your rule.

See [this gist](https://gist.github.com/abargnesi/fb74c992adb0dbaff4f1) as an example.
