### ISSUE TITLE
namespaced DSL

### ISSUE THREAD

**Issue by tonywok** [ulfurinn/wongi-engine#41]
Would you accept a PR that wraps the dsl in a module? Just so the methods aren't defined on `Object`.

For example:

```ruby
module MyModule
  extend Wongi::DSL # or include
  # ...
  rule "foo" do
    # ...
  end
end
```
If not willing, what's your motivation for putting them at the top level? I suppose one downside is that it could break other peoples' code who are relying on it being on `Object`?

Thanks :)

**Comment by ulfurinn** [comment]
Oh, totally. I've been meaning to do that for ages.

It would be nice to keep the current top-level methods available for now to provide a migration path. Something like this in dsl.rb:

```ruby
module Wongi::Engine::DSL
  # moved methods
end
module Wongi::Engine::DSL::Deprecation
  def ruleset name = nil, &definition
    # emit deprecation message
    super
  end
  # ...
end

class Object
  include Wongi::Engine::DSL
  include Wongi::Engine::DSL::Deprecation
end
```

**Comment by tonywok** [comment]
Yeah, seems like a good idea to me. I'll take a stab at it.

Also, while I have you, are rule definitions (i.e the block) evaluated immediately, or when they are added to the engine? I'm trying to find a way to version rules and it would be nice to only evaluate the blocks for the rules in the "current version".

**Comment by tonywok** [comment]
https://github.com/ulfurinn/wongi-engine/pull/42
