### ISSUE TITLE
wongi v0.1.1 and faraday

### ISSUE THREAD

**Issue by rodolfospalenza** [ulfurinn/wongi-engine#44]
Hello,

In the new version of wongi (v0.1.1) I note that you open `Object` class and include `Wongi::Engine::DSL` module.

```ruby
class Object
  warn "[DEPRECATION] Future versions of wongi-engine will not define dsl on Object. Please `include Wongi::Engine::DSL` going forward."
  include Wongi::Engine::DSL
end
```

It caused a problem with `faraday` gem. Faraday executes the code below:

```ruby
def url(path, params = nil)
  if path.respond_to? :query
    if query = path.query
      path = path.dup
      path.query = nil
    end
...
```

The `query` method is called without params, raising this exception:

```
wrong number of arguments (0 for 1)
```

I think that was not a good idea open the `Object` class and include `Wongi::Engine::DSL` module. I had to rollback version to fix my problem.

**Comment by ulfurinn** [comment]
Yanked the whole thing from rubygems, can't find a way of preserving original behaviour. Will be a breaking change in 0.2.0.

**Comment by tonywok** [comment]
Thanks for yanking, @ulfurinn. Yeah, I was dissatisfied with the strategy, but also struggled to find a reasonable way to preserve global dsl. Sorry if I caused you some grief.
