### ISSUE TITLE
Data overlays

### ISSUE THREAD

**Issue by ulfurinn** [ulfurinn/wongi-engine#45]
This is something I've had on my mind for a while, and going through old tickets I saw similar concerns from other people, so I decided to get something written.

Generally, a rule engine should be compiled once and reused, because compiling a large rule base can be expensive. However, up until now, data was stored inside logic elements, which means that if you do want to reuse an engine instance, you need to retract all asserted facts, will which retrigger rule execution, which is also expensive.

Data overlays separate facts from logic elements, allowing a user to quickly wipe data from en engine instance.

[A minimal example](https://github.com/ulfurinn/wongi-engine/blob/cef889c00e1300ce92f9b91c36e8111e32230563/spec/overlay_spec.rb)

Overlays can be stackable indefinitely, for data with different lifetimes. `#<<` called on the engine instance will add facts to `#default_overlay`, which is globally visible and permanent.

This is intended for 0.2.0.

**Comment by tonywok** [comment]
This looks great so far - definitely a welcomed feature.

I'm assuming rules that make use of `make { gen :Some, :Derived, :Data }` will add data to the current overlay. Is that correct?

**Comment by abargnesi** [comment]
+1. This would be a performance benefit for my use case. I would like to have a single engine for the life of the ruby process that I could repeatedly assert a set of facts and obtain the inferred facts for only that set.

**Comment by ulfurinn** [comment]
> I'm assuming rules that make use of make { gen :Some, :Derived, :Data } will add data to the current overlay. Is that correct?

Indeed. More generally, the earliest overlay that would be logically consistent.

**Comment by cosmocracy** [comment]
+1.  I'm considering an application to help analyze some research data.  Being able to have an overall data context--with a disposable local-subcontext--would allow me to assert a number of facts that are generally true (e.g., about biospecimen types, study protocols, etc.) and have an easy way to only keep the facts for each study subject in working memory as long as I need them to make inferences.  In this case I'm rolling through a list of study subjects serially.

**Comment by ulfurinn** [comment]
@cosmocracy is there something you need that is not covered by the [existing functionality](http://ulfurinn.github.io/wongi-engine/04-overlays.html)?
