### ISSUE TITLE
Best approach for creating a rule that accomplishes a reduce operation

### ISSUE THREAD

**Issue by caldwecr** [ulfurinn/wongi-engine#47]
Consider this simple scenario

```ruby
# 0 or more facts with "age" predicate
engine << ["mary", "age", 15]
engine << ["paul", "age", 22]
engine << ["fred", "age", 71]
```

I would like to make gen a new fact that contains the cumulative age of all of the persons (or the average, or any arbitrary reduce block)

My current (presumably naive) approach is to consolidate pairs into incremental "generations"

Let's take the cumulative age example (this is not an implementation, just a series of generations and facts to express how the algorithm works):
```ruby
# Generation 0
["mary", "age", 15]
["mary", "generation", 0]
["paul", "age", 22]
["paul", "generation", 0]
["fred", "age", 71]
["fred", "generation", 0]

# Sum each tuple of facts (a,b), (b, a), (a,c), (c, a), (b,c), (c,b)
# concatenate the subjects in alphabetical order (to avoid duplicates)
# as the subjects of the new generation

# Generation 1
["mary&paul", "age", 37]
["mary&paul", "generation", 1]
["fred&mary", "age", 86]
["fred&mary", "generation", 1]
["fred&paul", "age", 93]
["fred&paul", "generation", 1]

# Generation 2
["fred&mary&paul", "age", 108]
["fred&mary&paul", "generation", 2]
```

This approach seems pretty lousy.

Is there a proper way to perform a reduce and make-gen?

**Comment by ulfurinn** [comment]
Not really. Not sure there should be, either.

**Comment by caldwecr** [comment]
Ok thank you. Just wanted to check before proceeding down a custom approach. We actually use this kind of thing for consolidating Subjects that we determine are duplicates that only appear slightly different.

Reaching out of our problem space for a minute, here's an example where a reduction of many to one might make sense:

For example consider 10 news articles about a particular football (soccer) match. We might consolidate those ten articles into a single match entity; to do that we could use wongi to determine which of the ten articles describe the same match and to decide how to consolidate them.
