### ISSUE TITLE
Token Comparison Not working

### ISSUE THREAD

**Issue by dinilv** [ulfurinn/wongi-engine#52]
Hi,

in my project am using rails and used below code to check the budget is going positive or not . But the variable comparison is not working . Any ideas? 

		@@engine.rule("Positive Budget Rule") do
    	forall {
        	has :id, "budget-expect", :num1
        	has :id, "budget-actual", :num2
        	greater :num1, :num2
   		}   		
   		make {
    		gen "result", "Postitive Trends", :id
  		}
		end

**Comment by ulfurinn** [comment]
Variables must start with a capital letter.

**Comment by dinilv** [comment]
Thanks a lot.. i have fixed that. One more quick question .. whether i can add arithmetic over these variables ? or should i use expression as below is the right way ?


		@@engine.rule("Positive Budget Rule") do
    	forall {
        	has :id, "budget-expect", :Num1
        	has :id, "budget-actual", :Num2
        	greater :Num1, :Num2
   		}   		
   		make {
    		
    		change=0
    		action { |token|
    			if token[:Num2].to_f >0
    				change=((token[:Num2].to_f-token[:Num1].to_f)*100.to_f)/(token[:Num2].to_f)
          		end
      		}

      		gen :id, "result", "Your  spend is on Positive Trend. :-)."
      		gen :id, "budget-change", change 
      		
  		}

**Comment by ulfurinn** [comment]
The content of `make` is evaluated once during rule compilation. `change` in your last `gen` clause is forever bound to `0`.

Use an `assign` block to capture the result of your expression in a token variable and then use it in `gen`.

**Comment by ulfurinn** [comment]
```ruby
forall {
  ...
  assign :Change do ... end
}
make {
  gen :Id, "budget-change", :Change
}
```

**Comment by dinilv** [comment]
Hi,
I am sorry to disturb u again. :-(

Could u tell me wts wrong with my expression?

		@@engine.rule("Positive Budget Rule") do
    	forall {
        	has :id, "budget-expect", :Num1
        	has :id, "budget-actual", :Num2
        	greater :Num1, :Num2
        	assign :Change do 
        		:Num2-:Num1*100/:Num2
        	 end
   		}   		
   		make {
    		
      		gen :id, "result", "Your campaign spend is on Positive Trend. :-)."
      		gen :id, "budget-change", :Change 
      		
  		}
		end

**Comment by ulfurinn** [comment]
```ruby
assign :Change do |token|
  token[:Num2]-token[:Num1]*100/token[:Num2]
end
```

:Num1 is still just a symbol, you can't do arithmetic on it...

**Comment by dinilv** [comment]
Thanks a lot.. Can you tell engine.clear or similar command will erase all facts and generated tokens on the engine ?

**Comment by ulfurinn** [comment]
Make a new engine or use overlays if your ruleset is expensive to compile.
https://github.com/ulfurinn/wongi-engine/blob/cef889c00e1300ce92f9b91c36e8111e32230563/spec/overlay_spec.rb

**Comment by dinilv** [comment]
Thanks a lot for looking into my query .. 💯
