### ISSUE TITLE
Error while trying to use ANY { option {}} instead of has

### ISSUE THREAD

**Issue by gakshay** [ulfurinn/wongi-engine#54]
Hello,

I'm trying to use ANY { option {}} and getting this error:
`gems/wongi-engine-0.2.7/lib/wongi-engine/dsl/any_rule.rb:14:in 'option': uninitialized constant Wongi::Engine::DSL::AnyRule::VariantRule (NameError)`

Need help in implementing this use case. Say user hate yogurt or cheese or any other milk product, need to generate a triplet {:User, "Milk", :Product}. Unable to make it work and Variant Rule error is also stoping to move forward

```
milk_products = WEngine.rule "milk-products" do
  forall {
    any {
      option {
        has :User, "yogurt", :Product
        has :User, "cheese", :Product
      }
    }
  }
  make {
    gen :User, "Milk", :Product
  }
end
```

**Comment by gakshay** [comment]
I'm using ruby 2.2.2 and just cloned your repo and rspec worked smooth especially for any_rule_spec.rb 👍 

While trying to use any { option {}}  is giving above error. One solution is to rename class

`class DSL::VariantRule < DSL::Rule` to
`class DSL::AnyRule::VariantRule < DSL::Rule` and it worked fine. However it's kinda hack and wouldn't like to create a PR for it

**Comment by ulfurinn** [comment]
fixed on 0.2.8

**Comment by gakshay** [comment]
Many thanks :) I have overridden the class in my project will remove that and use the latest code. 

Thanks again!

**Comment by gakshay** [comment]
Just wondering why none of the `any{option{}}` spec failed because of this.

**Comment by ulfurinn** [comment]
Because all the specs include the DSL module.

**Comment by ulfurinn** [comment]
Specs use DSL#rule instead of Engine#rule. The blocks are evaluated in different scopes.
