### ISSUE TITLE
using assign for a false bool value causes 'DefinitionError: unbound variable'

### ISSUE THREAD

**Issue by mcneilm4** [ulfurinn/wongi-engine#55]
I am creating a rule that should generate new facts.

```
rule :get_customer_facts do
  for_all {
    has :base_fact, :customer_id, :CustomerId
    assign :Customer do |token|
      Customer.find(token[:CustomerId])
    end
    assign :IsFrozen do |token|
      token[:Customer].frozen? # frozen? returns false
    end
  }
  make {
    gen :CustomerId, :customer_is_frozen, :IsFrozen
  }
```

When .frozen? returns false in the :IsFrozen assignment, then I get the following error:
`Wongi::Engine::DefinitionError: unbound variable IsFrozen in token TOKEN [ 70248794866740 parent=70248783279520 CustomerId => object of {:base_fact :customer_id 40000010} Customer => #<Customer::Unit:0x007fc8238c6b10> IsFrozen => false ]`

**Comment by ulfurinn** [comment]
Oops.

**Comment by ulfurinn** [comment]
Pushed v0.2.9.
