### ISSUE TITLE
Tutorial example gives error

### ISSUE THREAD

**Issue by kinezu** [ulfurinn/wongi-engine#58]
This example in the tutorial does not seem to work when I combine rules:

```
my_ruleset = ruleset {
    rule "rule 1" do
        ...
    end
    rule "rule 2" do
        ...
    end
}

engine << my_ruleset
```

I get this:

```
undefined method `ruleset' for main:Object (NoMethodError)
```

Any help or clarity in the doc would be appreciated.

**Comment by ulfurinn** [comment]
Oh yes. `include Wongi::Engine::DSL` is required since a few releases back, I never updated the tutorial for this.
