### ISSUE TITLE
Finding latest fact by date?

### ISSUE THREAD

**Issue by chezsmithy** [ulfurinn/wongi-engine#60]
Are there any temporal operations where I could for example find the latest fact based on a date.

So for example:

Claim1, "is", "Claim"
Claim2, "is", "Claim"
Claim3, "is", "Claim"

Claim1, "dateofservice", 1/1/2016
Claim2, "dateofservice", 2/1/2016
Claim3, "dateofservice", 3/1/2016

Can I ask the engine to return the latest Claim or the earliest Claim?

**Comment by ulfurinn** [comment]
There are no universal operations, but you can usually rephrase then into an existential one with a negation.
Something like this (off the top of my head, may not execute as is):

```ruby
forall {
  has :Claim1, :is, :claim
  has :Claim1, :dateofservice, :Date1
  none {
    has :Claim2, :is, :claim
    has :Claim2, :dateofservice, :Date2
    greater :Date2, :Date1
  }
}
```

Translated back to human, "there does not exist any such claim that is more recent than Claim1"
