### ISSUE TITLE
How to retract a fact upon matching action?

### ISSUE THREAD

**Issue by evanchaoli** [ulfurinn/wongi-engine#70]
The documentation says:

`Avoid modifying the engine inside action blocks (i.e., asserting and retracting facts and installing new rules). There are safer ways of doing this. `

I see the better way to assert fact upon matching action is to use gen. But I don't see how to retract facts.

**Comment by ulfurinn** [comment]
You could achieve that by having helper facts with an inverted predicate, like:

```ruby
forall {
  # bind X and Y
  missing :X, :not_p, :Y
}
make {
  gen :X, :p, :Y
}
```

Then in your main rule you can invalidate this condition with `gen :X, :not_p, :Y` and so effectively retract `{X, p, Y}`.

Don't know if this will work for your data model.

It's clunky, but I can't see a better solution without building support for some kind of negative facts.

As a last resort, you _can_ make direct changes with action blocks, but then the engine will not be able to keep track of relationships, which may affect logical consistency of the data set.
