### ISSUE TITLE
what is the benefit of using Wongi

### ISSUE THREAD

**Issue by amitdotagarwal** [ulfurinn/wongi-engine#73]
Hi All,

I have implemented Wongi gem for our rule engine. However, I am unable to understand what all benefits of using this, as every time I load the data from the database to process data in the Wongi gem. 

So, isn't better to use SQL to fetch relevant data from the database, instead of process two time with Wongi?
Please let me know your thoughts.

Thanks,
Amit

**Comment by chrstphrhrt** [comment]
@amitdotagarwal I have not used this lib yet but in general, Rete is more efficient at processing all the possible breadth-first searches that go into finding what questions can be answered by the given facts. It's not about trying to optimize a known solution, it's about finding possible solutions. The opposite is backward chaining which is straight deduction, in which you find the best answer to a given question/query (depth first search of matching properties), analogous to a normal SQL query. Postgres has recursive CTEs which can partially bridge this gap by iteratively querying stuff until it hits one or more "bottom" datasets. Or like you suggest, it's fine to just keep generating deeper and deeper queries based on new input, just not efficient when dealing with lots of possible paths compared to Rete which AFAIK memoizes where it has been along the way to make it faster (specialized caching). I'm unclear on what kind of algos the recursive CTEs are using in the Postgres query planner, maybe there are similarities. For me the benefit of Rete is being able to process rules and facts as pure data, which means the behaviour can be configured by users. Writing a generic, recursive breadth-first solution finder sounds like a lot of work to me and I'd rather leave it to the real computer scientists :) I think something like LTREE in Postgres for storing DAG-based workflows and taxonomies, plus a Rete library or CLIPS-like system to traverse the stuff is a powerful way to make expert systems.

**Comment by clgiovannelli** [comment]
Hi @amitdotagarwal,
take a look to this [Martin Fowler](https://martinfowler.com/bliki/RulesEngine.html ) article, old but still valid.

D.
