### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by thirumal1** [ulfurinn/wongi-engine#75]
I have started to use wongi-engine for a project.
I have understood the concepts, want to get a idea of how to integrated in rails app, and  is there a link to larger examples of wongi-engine use?

Thanks in advance.
Rao

**Comment by thirumal1** [comment]
s

**Comment by kittrCZ** [comment]
Hello @thirumal1,

have you ever get a response on your question? I'm looking for a way to integrate the Wongi::Engine into my application as well, but there is a lack of resources on how to integrate it into a rails application.

Any help appreciated.
