### ISSUE TITLE
Issues with `Network#remove_production`

### ISSUE THREAD

**Issue by ricksuggs** [ulfurinn/wongi-engine#84]
I've been experimenting with removing rules from an engine after all facts have been loaded, but quickly noticed that an undefined method was being called on `Wongi::Engine::Token`, resulting in the following error:

```ruby
NoMethodError:
   undefined method `delete' for #<Wongi::Engine::Token:0x00007fca2c2dd1d0>
 # ./lib/wongi-engine/network.rb:401:in `delete_node_with_ancestors'
 # ./lib/wongi-engine/network.rb:278:in `remove_production'
 # ./spec/network_spec.rb:54:in `block (2 levels) in <top (required)>'
```

I changed `Wongi::Engine::Network#delete_node_with_ancestors` to call `Wongi::Engine::Token#destroy` which initially seemed to fix the issue.

However, I have a test where a rule is removed, then another rule is added. The test fails to find tokens for the new rule when a previous rule has been removed.

[Here](https://github.com/ulfurinn/wongi-engine/compare/master...ricksuggs:wongi-engine:bugfix/remove_production_does_not_work) is the branch where I have added the tests.

Any thoughts?

P.S. Thank you for building and maintaining this.

**Comment by ulfurinn** [comment]
Hi,

Sorry, took me a while to summon the energy.
Fixed in master, I’ll cut a release a bit later unless you need it urgently. Thanks for the tests.

You’re a brave man to play with undocumented APIs.

/Valeri
