### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by onslauth** [ulfurinn/wongi-engine#86]
Ruby: 3.1.2p20
wongi-engine: 0.4.1

Tried the following code from `ex01.rb`:
```Ruby
include Wongi::Engine

ds = Network.new

ds << WME.new("Alice", "friend", "Bob")

puts "Enumerate all:"

ds.each do |wme|
  puts wme
end
```

Output:
```
$ ruby ./rules.rb 
Enumerate all:
$ 
```

Also read through the tutorial, and the code there produces the same result. Is there a further step that is missing here?

**Comment by ulfurinn** [comment]
Pushed v0.4.3, well caught.
