### ISSUE TITLE
What happened to engine.entity?

### ISSUE THREAD

**Issue by UfiAuttorri** [ulfurinn/wongi-engine#87]
The following Entity iterator is missing (or so it seems):

alice = engine.entity("Alice")

It throws: NoMethodError: undefined method 'entity' for <Rete>:Wongi::Engine::Network

Was it removed or replaced and if so, is there now a different way to accomplish the same thing?

Thank you,
UA

**Comment by ulfurinn** [comment]
Nothing happened to it, it's right there. A bigger code snippet might be helpful for reproduction.

**Comment by UfiAuttorri** [comment]
Thanks for the reply.  Perhaps we are doing something incorrectly.  Here is the ruby script and the pry output in question.  The missing pieces are inconsequential (in our opinion).  It simple says "undefined method 'entity" ... all the other methods show up but not that particular construct.  Are we invoking it incorrectly?  We copied this from the tutorial.


----- SCRIPT
#wongi-engine-rete-test.rb

require 'wongi-engine'
engine = Wongi::Engine.create

# assert some facts
engine << ["Alice", :friend, "Bob"]
engine << ["Alice", :age, 35]

# retract a fact
engine.retract ["Alice", :age, 35]

# list everything we know about Alice
engine.each("Alice", :_, :_) do |elem|
  puts "Alice's #{elem.predicate} is #{elem.object}"
end

alice = engine.entity("Alice")

...  OUTPUT

----- *REPL*[ruby]
...
[3] pry(main)> [3] pry(main)* => nil
[4] pry(main)> [4] pry(main)* => nil
[5] pry(main)> [5] pry(main)* => nil
[6] pry(main)> [6] pry(main)* Alice's friend is Bob
=> [#<struct Wongi::Engine::WME subject="Alice", predicate=:friend, object="Bob">]
[7] pry(main)> [7] pry(main)* NoMethodError: undefined method 'entity' for <Rete>:Wongi::Engine::Network
from (eval):1:in '<main>'
[8] pry(main)>

**Comment by ulfurinn** [comment]
Check the version you're on. Entity iterators were added in 0.4.x.

**Comment by UfiAuttorri** [comment]
Aha!  That must be the problem.  We installed an existing ruby gem from "the list" ... just checked it and it shows: mort666-wongi-engine (0.2.9)

So, clearly outdated.  Sorry to waste your time.  We should have thought to check that first thing.
